import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

clientsClaim();
self.skipWaiting();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// SPA fallback - this will throw in dev mode because index.html is not precached
try {
  const handler = createHandlerBoundToURL('/index.html');
  const navigationRoute = new NavigationRoute(handler, {
    denylist: [/^\/api\//],
  });
  registerRoute(navigationRoute);
} catch (e) {
  console.warn('SPA fallback not configured, this is expected in dev mode.');
}

// Runtime caching for Google Fonts
registerRoute(
  /^https:\/\/fonts\.googleapis\.com\/.*/i,
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

registerRoute(
  /^https:\/\/fonts\.gstatic\.com\/.*/i,
  new CacheFirst({
    cacheName: 'gstatic-fonts-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }),
    ],
  })
);

// Runtime caching for Images
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp|ico)$/i,
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 60 * 60 * 24 * 30 }),
    ],
  })
);

// --- Web Push Notifications ---

self.addEventListener('push', (event) => {
  if (!event.data) return;

  let title = 'New Notification';
  let body = '';
  let url = '/';

  try {
    const data = event.data.json();
    title = data.title || title;
    body = data.body || '';
    url = data.url || url;
  } catch (err) {
    // Fallback to text for dev-tools testing
    body = event.data.text();
  }

  const options = {
    body,
    icon: '/192x192.png',
    badge: '/192x192.png',
    data: { url },
  };

  event.waitUntil(self.registration.showNotification(title, options));
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  // Ensure url is absolute so we can match it against client.url
  const urlToOpen = new URL(event.notification.data?.url || '/', self.location.origin).href;

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Find a window that is already open to our site
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i];
        
        // If they already have the app open on any page, just focus it and navigate to the right tab
        if (client.url && 'focus' in client) {
          client.focus();
          if ('navigate' in client) {
            client.navigate(urlToOpen);
          }
          return;
        }
      }
      
      // If no window is open, open a new one
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
